name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: recursive
    
    # Install some dependencies for SFML
    - if: matrix.os == 'ubuntu-latest'
      name: Install SFML dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        libxrandr-dev \
        libxcursor-dev \
        libxi-dev \
        libudev-dev \
        libflac-dev \
        libvorbis-dev \
        libgl1-mesa-dev \
        libegl1-mesa-dev \
        libfreetype-dev \
        libharfbuzz-dev \
        libmbedtls-dev \
        libssh2-1-dev

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "workspace-dir=$(echo "${{ github.workspace }}" | sed 's|\\|/|g')" >> "$GITHUB_OUTPUT"
        echo "build-output-dir=$(echo "${{ github.workspace }}/build" | sed 's|\\|/|g')" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      shell: bash
      run: |
        rm -rf build
        cmake -S ${{ steps.strings.outputs.workspace-dir }} \
        -B ${{ steps.strings.outputs.build-output-dir }} \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
